<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="31.558" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2024-04-27T13:37:50" tests="0" file="cypress\e2e\secondTest.spec.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Test log out" timestamp="2024-04-27T13:37:50" tests="1" time="31.552" failures="1">
    <testcase name="Test log out verify use can log out successfully" time="6.618" classname="verify use can log out successfully">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up2&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up2'
    at Context.eval (webpack://realworld-app/./cypress/e2e/secondTest.spec.js:10:30)]]></failure>
    </testcase>
  </testsuite>
</testsuites>